// import {questionData } from './QuestionsType';

export const mockArray:any = [
  { 
    title: "This is the first question",
    questionId: 1, 
    questionText: "Question 1: Text",  
    choiceTextA: "Go to question 2", 
    choiceA: 2,
    choiceTextB: "Go to question 3",
    choiceB: 3,
    choiceTextC: "END HERE WITH END TEXT",
    choiceC: 1,
    endTextA: "",
    endTextB: "",
    endTextC: "SHOW ME TEXT"
  },
  { 
    title: "This is the second question",
    questionId: 2, 
    questionText: "Question 2: Text", 
    choiceTextA: "Go to question 3", 
    choiceA: 3, 
    choiceTextB: "Also go to the next question",
    choiceB: 3,
    choiceTextC: "END HERE WITHOUT END TEXT",
    choiceC: 2,
    endTextA: "",
    endTextB: "",
    endTextC: "This is the end of the series: Choice C was made"
  },
  { 
    title: "This is the third question",
    questionId: 3, 
    questionText: "Question 3: Text", 
    choiceTextA: "End text will appear for A", 
    choiceA: 3, 
    choiceTextB: "End text will appear for B",
    choiceB: 3,
    choiceTextC: "This goes to Question 4",
    choiceC: 4,
    endTextA: "This is the end of the series: Choice A was made",
    endTextB: "This is the end of the series: Choice B was made",
    endTextC: ""
  },
  { 
    title: "This is the fourth question",
    questionId: 4, 
    questionText: "Question 4: Text", 
    choiceTextA: "Will move on to Question 5", 
    choiceA: 5, 
    choiceTextB: "End text will appear for B",
    choiceB: 4,
    choiceTextC: "",
    choiceC: null,
    endTextA: "",
    endTextB: "This is the end of the series: Choice B was made",
    endTextC: ""
  },
  { 
    title: "This is the fifth question",
    questionId: 5, 
    questionText: "Question 5: Text", 
    choiceTextA: "Will move on to Question 11", 
    choiceA: 11, 
    choiceTextB: "Will move on to Question 6",
    choiceB: 6,
    choiceTextC: "End text will appear for C",
    choiceC: 5,
    endTextA: "",
    endTextB: "",
    endTextC: "End text for C"
  },
  { 
    title: "This is the sixth question",
    questionId: 6, 
    questionText: "Question 6: Text", 
    choiceTextA: "Will move on to Question 7",
    choiceA: 7, 
    choiceTextB: "End text will appear for 6",
    choiceB: 6,
    choiceTextC: "Will move on to Question 10",
    choiceC: 10,
    endTextA: "",
    endTextB: "This is the end of the series: Choice B was made",
    endTextC: ""
  },
  { 
    title: "This is the seventh question",
    questionId: 7, 
    questionText: "Question 7: Text", 
    choiceTextA: "Will move on to Question 8", 
    choiceA: 8, 
    choiceTextB: "Will move on to Question 9",
    choiceB: 9,
    choiceTextC: "",
    choiceC: null,
    endTextA: "",
    endTextB: "",
    endTextC: ""
  },
  { 
    title: "This is the eighth question",
    questionId: 8, 
    questionText: "Question 8: Text", 
    choiceTextA: "Will move on to Question 9",
    choiceA: 9, 
    choiceTextB: "End text will appear for B",
    choiceB: 8,
    choiceTextC: "",
    choiceC: null,
    endTextA: "",
    endTextB: "This is the end of the series: Choice B was made",
    endTextC: ""
  },
  { 
    title: "This is the nineth question",
    questionId: 9, 
    questionText: "Question 9: Text", 
    choiceTextA: "Will end with text A", 
    choiceA: 9, 
    choiceTextB: "Will move on to Question 10",
    choiceB: 10,
    choiceTextC: "",
    choiceC: null,
    endTextA: "End text for A",
    endTextB: "",
    endTextC: ""
  },
  { 
    title: "This is the tenth question",
    questionId: 10, 
    questionText: "Question 10: Text", 
    choiceTextA: "Will move on to Question 11", 
    choiceA: 11, 
    choiceTextB: "Will move on to Question 11",
    choiceB: 11,
    choiceTextC: "",
    choiceC: null,
    endTextA: "",
    endTextB: "",
    endTextC: ""
  },
  { 
    title: "This is the eleventh question",
    questionId: 11, 
    questionText: "Question 11: Text", 
    choiceTextA: "End text will appear for A", 
    choiceA: 11, 
    choiceTextB: "End text will appear for B",
    choiceB: 11,
    choiceTextC: "End text will appear for C",
    choiceC: 11,
    endTextA: "This is the end of the series: Choice A was made",
    endTextB: "This is the end of the series: Choice B was made",
    endTextC: "This is the end of the series: Choice C was made"
  }
];